### ISSUE TITLE
Custom DS920 

### ISSUE THREAD

**Issue by Mr-hsing** [wjz304/rpcb#49666]
{"model":"DS920+","version":"7.2.1-69057","jun":"1","lkm":"prod","maxlanport":"7","internalportcfg":"0xf","netif_num":"1","vid":"0x0781","pid":"0x5571","dtb":"https://github.com/wjz304/Redpill_CustomBuild/files/12215991/output.zip","addons":"acpid2,boot-wait,misc","modules":"r8169"}

**Comment by iphonetlbs** [comment]
delete builds
